import Head from "next/head";
import { AboutMeComponent } from "../Components/AboutMeComponent";

export default function AboutMe() {
  return (
    <>
      <Head>
        <title>Portfolio - About Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutMeComponent />
    </>
  );
}
