import Head from "next/head";
import { ContactComponent } from "../Components/ContactComponent";
export default function Contact() {
  return (
    <div>
      <Head>
        <title>Portfolio - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactComponent />
    </div>
  );
}
