import Head from "next/head";
import { ProjectsComponent } from "../Components/ProjectsComponent";
import { SectionContainer } from "../Components/layout/SectionContainer";

export default function Projects() {
  return (
    <div>
      <Head>
        <title>Portfolio - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionContainer>
        <ProjectsComponent />
      </SectionContainer>
    </div>
  );
}
